name: Build

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ '12', '16' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Prepare
      run: python prepare/main.py
    - name: Test
      run: npm test
    - name: Build documentation
      run: npm run doc:html
